[package]
name = "models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "1.3.0"
chrono = "0.4"
anyhow = "1.0"
futures = "0.3"
async-trait = "0.1.68"

scylla = "0.8.0"
sqlx = { version = "0.6.3", features = [ "runtime-tokio-native-tls", "postgres", "uuid" ] }

stream_helpers = { path = "../stream_helpers" }