version: '3.8'

services:
  scylladb:
    image: scylladb/scylla
    container_name: scylladb
    command: --smp 1 --developer-mode 1
    ports:
      - "9042:9042"
    volumes:
      - scylladb_data:/var/lib/scylla
      - ./scylla.yaml:/etc/scylla/scylla.yaml
      - ./migration:/usr/migration
    environment:
      - SCYLLA_CLUSTER_NAME=my_social_network_cluster
      - SCYLLA_ENDPOINT_SNITCH=SimpleSnitch

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration:/usr/migration
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_social_network_db

volumes:
  scylladb_data:
  postgres_data: